controller_list:
  - name: fake_arm_controller
    joints:
      - base_x_base_y
      - base_theta_base_x
      - base_link_base_theta
      - ur_arm_shoulder_pan_joint
      - ur_arm_shoulder_lift_joint
      - ur_arm_elbow_joint
      - ur_arm_wrist_1_joint
      - ur_arm_wrist_2_joint
      - ur_arm_wrist_3_joint