<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:macro name="cabinet" params="prefix attach_to_world loc_x loc_y orientation">

    <xacro:property name="cabinet_height" value="1.06" />
    <xacro:property name="cabinet_width" value="0.28" />
    <xacro:property name="cabinet_depth" value="0.40" />
    <xacro:property name="cabinet_x" value="1.5" />
    <xacro:property name="cabinet_y" value="0.0" />
    <xacro:property name="cabinet_z" value="0.0" />

    <xacro:if value="${attach_to_world}">
      <joint name="${prefix}world" type="fixed">
        <child link="${prefix}base_link" />
        <parent link="world" />
        <origin xyz="${loc_x} ${loc_y} 0.0" rpy="0.0 0.0 ${orientation}"/>
      </joint>
    </xacro:if>

    <!-- base_link -->
    <link name="${prefix}base_link">
      <inertial>
        <origin xyz="0 0 0" />
        <mass value="5.0" />
        <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" />
        <geometry>
          <box size="0.00 0.00 0.00" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" />
        <geometry>
          <box size="0.00 0.00 0.00" />
        </geometry>
      </collision>
    </link>


    <!-- cabinet -->

    <!-- cabinet_structure -->
    <link name="${prefix}cabinet_structure">
      <inertial>
        <origin xyz="0 0 0" />
        <mass value="5.0" />
        <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" />
        <geometry>
          <box size="${cabinet_width} ${cabinet_depth} ${cabinet_height}" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" />
        <geometry>
          <box size="${cabinet_width} ${cabinet_depth} ${cabinet_height}" />
        </geometry>
      </collision>
    </link>

    <gazebo reference="cabinet_structure">
      <material>Gazebo/White</material>
    </gazebo>

    <joint name="${prefix}joint_structure" type="fixed">
      <origin xyz="0.000 0.000 ${cabinet_height/2}" rpy="0 0 0" />
      <parent link="${prefix}base_link" />
      <child link="${prefix}cabinet_structure" />
    </joint>



    <!-- cabinet_door -->
    <link name="${prefix}cabinet_door">
      <inertial>
        <origin xyz="0 0 0" />
        <mass value="1.0" />
        <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
      </inertial>
      <visual>
        <origin xyz="0 ${-cabinet_depth/2} 0" />
        <geometry>
          <box size="0.02 ${cabinet_depth} ${cabinet_height-0.08}" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 ${-cabinet_depth/2} 0" />
        <geometry>
          <box size="0.02 ${cabinet_depth} ${cabinet_height-0.08}" />
        </geometry>
      </collision>
    </link>

    <gazebo reference="cabinet_door">
      <material>Gazebo/White</material>
    </gazebo>

    <joint name="${prefix}joint_door" type="revolute">
      <origin xyz="${-cabinet_width/2} ${cabinet_depth/2} 0.04" rpy="0 0 0" />
      <parent link="${prefix}cabinet_structure" />
      <child link="${prefix}cabinet_door" />
      <axis xyz="0 0 1"/>
      <limit lower="-3.14" upper="0" effort="20" velocity="5"/>
    </joint>

    <!--knob1-->
    <link name="${prefix}knob1_link">
      <inertial>
        <origin xyz="0 0 0" />
        <mass value="1.0" />
        <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" />
        <geometry>
          <box size="0.03 0.015 0.01" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" />
        <geometry>
          <box size="0.03 0.015 0.01" />
        </geometry>
      </collision>
    </link>

    <gazebo reference="knob1_link">
      <material>Gazebo/Grey</material>
    </gazebo>

    <joint name="${prefix}joint_knob1" type="fixed">
      <origin xyz="${-0.015} ${-cabinet_depth+0.0175} ${(0.0)/2-0.0}" rpy="0 0 0" />
      <parent link="${prefix}cabinet_door" />
      <child link="${prefix}knob1_link" />
    </joint>

    <!--knob2-->
    <link name="${prefix}knob2_link">
      <inertial>
        <origin xyz="0 0 0" />
        <mass value="1.0" />
        <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" />
        <geometry>
          <box size="0.03 0.015 0.01" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" />
        <geometry>
          <box size="0.03 0.015 0.01" />
        </geometry>
      </collision>
    </link>

    <gazebo reference="knob2_link">
      <material>Gazebo/Grey</material>
    </gazebo>

    <joint name="${prefix}joint_knob2" type="fixed">
      <origin xyz="${-0.015} ${-cabinet_depth+0.0175} ${(0.0)/2-0.0-0.13}" rpy="0 0 0" />
      <parent link="${prefix}cabinet_door" />
      <child link="${prefix}knob2_link" />
    </joint>

    <!--knob3-->
    <link name="${prefix}knob3_link">
      <inertial>
        <origin xyz="0 0 0" />
        <mass value="1.0" />
        <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" />
        <geometry>
          <box size="0.01 0.015 0.14" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" />
        <geometry>
          <box size="0.01 0.015 0.14" />
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}joint_knob3" type="fixed">
      <origin xyz="-0.02 0 -0.065" rpy="0 0 0" />
      <parent link="${prefix}knob1_link" />
      <child link="${prefix}knob3_link" />
    </joint>

  </xacro:macro>
</robot>