<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:macro name="table" params="prefix attach_to_world loc_x loc_y orientation">

    <xacro:property name="table_height" value="0.74" />
    <xacro:property name="table_width" value="0.9" />
    <xacro:property name="table_depth" value="0.9" />
    <xacro:property name="table_x" value="0.98" />
    <xacro:property name="table_y" value="0.0" />
    <xacro:property name="table_z" value="0.0" />

    <xacro:property name="table_top_thickness" value="0.04"/>

    <xacro:property name="M_PI" value="3.1415926535897931" />

    <xacro:if value="${attach_to_world}">
      <joint name="${prefix}world" type="fixed">
        <child link="${prefix}base_link" />
        <parent link="world" />
        <origin xyz="${loc_x} ${loc_y} 0.0" rpy="0.0 0.0 ${orientation}"/>
      </joint>
    </xacro:if>

    <link name="${prefix}base_link">
      <inertial>
        <mass value="5.0" />
        <origin xyz="0.0 0.0 0.0" />
        <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0" />
      </inertial>
      <visual>
        <origin xyz="0.0 0.0 ${table_z+table_height-table_top_thickness/2}" />
        <geometry>
          <box size="${table_width} ${table_depth} ${table_top_thickness}" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0.0 0.0 ${table_z+table_height-table_top_thickness/2}" />
        <geometry>
          <box size="${table_width} ${table_depth} ${table_top_thickness}" />
        </geometry>
      </collision>
    </link>

    <xacro:macro name="legs" params="suffix parent pos1 pos2">

      <link name="${prefix}leg_${suffix}_link">
        <inertial>
          <origin xyz="0 0 0" />
          <mass value="3" />
          <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0" />
        </inertial>

        <visual>
          <origin xyz="0 0 0" />
          <geometry>
            <box size="0.055 0.055 ${table_height-table_top_thickness}" />
          </geometry>
        </visual>

        <collision>
          <origin xyz="0 0 0" />
          <geometry>
            <box size="0.055 0.055 ${table_height-table_top_thickness}" />
          </geometry>
        </collision>
      </link>

      <joint name="leg_${suffix}_joint" type="fixed">
        <parent link="${prefix}base_link" />
        <origin xyz="${0.0+pos1*(table_width/2-0.0375)} ${table_y+pos2*(table_depth/2-0.0375)} ${table_z+table_height/2}" rpy="0 0 0" />
        <child link="${prefix}leg_${suffix}_link" />
      </joint>


    </xacro:macro>
    <legs suffix="left_front" parent="base_link" pos1="1" pos2="1"/>
    <legs suffix="left_back" parent="base_link" pos1="-1" pos2="1"/>
    <legs suffix="right_front" parent="base_link" pos1="1" pos2="-1"/>
    <legs suffix="right_back" parent="base_link" pos1="-1" pos2="-1"/>

    <xacro:macro name="structure_lath" params="suffix parent pos1 pos2 box_size">


      <link name="${prefix}lath_${suffix}_link">
        <inertial>
          <origin xyz="0 0 0" />
          <mass value="1" />
          <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0" />
        </inertial>

        <visual>
          <origin xyz="0 0 0" />
          <geometry>
            <box size="${box_size}" />
          </geometry>
        </visual>

        <collision>
          <origin xyz="0 0 0" />
          <geometry>
            <box size="${box_size}" />
          </geometry>
        </collision>
      </link>

      <joint name="${prefix}lath_${suffix}_joint" type="fixed">
        <parent link="${prefix}base_link" />

        <origin xyz="${0.0+pos1*(table_width/2-0.02)} ${table_y+pos2*(table_depth/2-0.02)} ${table_z+table_height-table_top_thickness-0.035}" rpy="0 0 0" />
        <child link="${prefix}lath_${suffix}_link" />
      </joint>

    </xacro:macro>

    <structure_lath suffix="left_front" parent="${prefix}base_link" pos1="1" pos2="0" box_size="0.02 0.77 0.07"/>
    <structure_lath suffix="left_back" parent="${prefix}base_link" pos1="-1" pos2="0" box_size="0.02 0.77 0.07"/>
    <structure_lath suffix="right_front" parent="${prefix}base_link" pos1="0" pos2="1" box_size="0.77 0.02 0.07"/>
    <structure_lath suffix="right_back" parent="${prefix}base_link" pos1="0" pos2="-1" box_size="0.77 0.02 0.07"/>
  </xacro:macro>
</robot>